# Generated by Django 4.2.1 on 2023-07-15 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('referencia', models.TextField()),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': 'componentes',
            },
        ),
    ]
